// Core product and content data for D3: Digital Data Dimensions (static source of truth)
// All content verified against dthree.co — do not add features or claims not on the original site.

export const SOLUTIONS = [
  {
    slug: 'time-attendance-system',
    num: '01',
    title: 'Time Attendance: Standard',
    desc: 'TimeTech biometric fingerprint, face recognition and card-based attendance with real-time processing, auto-shift picking, LMRA-compliant payroll export and unlimited sites.',
    tags: ['Biometric', 'LMRA Ready', 'Auto Shift', 'Mobile App'],
    icon: 'clock',
  },
  {
    slug: 'time-attendance-enterprise',
    num: '02',
    title: 'Time Attendance: Enterprise',
    desc: 'No.1 TimeTech. Multi-site, multi-company enterprise attendance for unlimited locations, with project manhour tracking, geo-fenced mobile app and full self-service portal.',
    tags: ['Multi-Site', 'Mobile App', 'Geo-Fencing', 'Project Manhours', 'Self-Service'],
    icon: 'clock',
  },
  {
    slug: 'hr-payroll-software',
    num: '03',
    title: 'HRMS',
    desc: 'TimeTech professional HRMS and Payroll for the Gulf Region. Multi-company, multi-currency, bi-lingual, flexible and cost effective. Covers the complete employee lifecycle.',
    tags: ['Multi-Company', 'GOSI Ready', 'WPS Export', 'Self-Service', 'Mobile App', 'Appraisal'],
    icon: 'users',
  },
  {
    slug: 'visitor-management',
    num: '04',
    title: 'Visitor Management System',
    desc: 'TimeTech professional and advanced online visitor management: reception kiosk, pre-registration, access card issuance, door assignment and full audit trail.',
    tags: ['Access Card Integration', 'Pre-Registration', 'Audit Trail'],
    icon: 'users',
  },
  {
    slug: 'queue-management-system',
    num: '05',
    title: 'Queue Management System',
    desc: 'TimeTech wired and wireless kiosk-based queue management with audio announcements, multi-service categories, counter LED displays and live analytics for ministries and enterprises.',
    tags: ['Kiosk', 'Wired & Wireless', 'Audio Announcements', 'Analytics'],
    icon: 'users',
  },
  {
    slug: 'digital-signage',
    num: '06',
    title: 'Digital Signage & Displays',
    desc: 'TimeTech LED, LCD and vertical signage displays from 42" with 4K support, 24/7 operation, centralized CMS, Android OS and optional touch screen for indoor and outdoor deployments.',
    tags: ['4K LED', 'Remote CMS', '24/7 Operation', 'eBook'],
    icon: 'monitor',
  },
  {
    slug: 'rfid-asset-tracking',
    num: '07',
    title: 'RFID & Asset Tracking',
    desc: 'TimeTech active and passive RFID tracking for assets, documents, warehouse inventory and gold ornaments across multiple buildings, departments and warehouses with mobile handheld terminal support.',
    tags: ['Active RFID', 'Warehouse WMS', 'Document Tracking', 'Mobile'],
    icon: 'layers',
  },
  {
    slug: 'access-control-system',
    num: '08',
    title: 'IP CCTV & Access Control',
    desc: 'TimeTech enterprise-grade IP surveillance cameras, biometric access controllers and proximity card systems integrated with centralized management software for GCC security compliance.',
    tags: ['IP Camera', 'Face Recognition', 'NFC / Proximity', 'Biometric'],
    icon: 'shield',
  },
  {
    slug: 'erp-retail-management',
    num: '09',
    title: 'ERP & Retail Management',
    desc: 'TimeTech full ERP covering procurement, inventory, sales, financial accounting, payroll, restaurant management and electronic shelf labels. Multi-company, multi-currency, multi-branch.',
    tags: ['Multi-Company', 'ESL', 'Inventory', 'Van Sales'],
    icon: 'briefcase',
  },
  {
    slug: 'consultancy',
    num: '10',
    title: 'IT Consultancy',
    desc: 'D3 provides outsourced IT staffing and consultancy for short-term projects, system implementations and ongoing managed service engagements across Bahrain and the GCC.',
    tags: ['Outsourced IT', 'ICT Planning', 'Managed Services', 'CISCO Certified'],
    icon: 'briefcase',
  },
];

export const INDUSTRIES = [
  {
    slug: 'government',
    title: 'Government',
    desc: 'Labour law compliance, LMRA integration, biometric attendance for civil service and ministry-grade physical security.',
    icon: 'building',
    challenges: [
      {
        title: 'LMRA & Labour Compliance',
        desc: 'Full alignment with Bahrain Labour Market Regulatory Authority requirements and Civil Service Bureau rules.',
      },
      {
        title: 'Large Distributed Workforce',
        desc: 'Managing thousands of employees across multiple ministries and government departments with centralised reporting.',
      },
      {
        title: 'Ministry-Grade Security',
        desc: 'Biometric access control, IP CCTV and visitor management for government facilities.',
      },
    ],
  },
  {
    slug: 'healthcare',
    title: 'Healthcare',
    desc: '24/7 shift scheduling, medical credential tracking, queue management for outpatient services and RFID equipment tracking.',
    icon: 'heart',
    challenges: [
      {
        title: '24/7 Shift Management',
        desc: 'Complex rotating schedules for doctors, nurses and support staff with Ramadan and special shift support.',
      },
      {
        title: 'Patient Queue Management',
        desc: 'Reducing waiting times in outpatient clinics and hospital departments with intelligent queue kiosks.',
      },
      {
        title: 'Credential & Document Tracking',
        desc: 'Maintaining up-to-date certifications, licenses and compliance documents with automated expiry reminders.',
      },
    ],
  },
  {
    slug: 'retail',
    title: 'Retail',
    desc: 'ERP, electronic shelf labels, real-time inventory control, workforce management and van sales for multi-location retailers.',
    icon: 'shopping-bag',
    challenges: [
      {
        title: 'Real-Time Inventory',
        desc: 'Live stock visibility across all locations with RFID and barcode scanning.',
      },
      {
        title: 'Electronic Shelf Labels',
        desc: 'Instant price updates across all shelves, eliminating manual repricing and pricing errors.',
      },
      {
        title: 'Workforce Management',
        desc: 'Shift scheduling and attendance management for multi-location retail staff with real-time reporting.',
      },
    ],
  },
  {
    slug: 'logistics',
    title: 'Logistics',
    desc: 'RFID warehouse management, asset tracking with handheld terminals, IP surveillance and distributed workforce management.',
    icon: 'truck',
    challenges: [
      {
        title: 'Warehouse & Asset Visibility',
        desc: 'RFID tracking across multiple warehouses with real-time stock levels and cycle counts.',
      },
      {
        title: 'Site Security',
        desc: 'IP CCTV monitoring for loading bays and warehouse areas.',
      },
      {
        title: 'Distributed Workforce',
        desc: 'Managing shift workers across multiple depots and sites with mobile attendance.',
      },
    ],
  },
];

// Real client projects — sourced verbatim from dthree.co homepage.
// These are the only verified project descriptions D3 publishes publicly.
// Do NOT add fabricated outcomes or made-up metrics.
export const CASE_STUDIES = [
  {
    slug: 'survey-land-registration-bureau',
    clientName: 'Survey & Land Registration Bureau',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Upgrade of Personnel, Leave, Employee Self Service and Time Attendance modules, including integration with Civil Service Bureau.',
  },
  {
    slug: 'labour-market-regulatory-authority',
    clientName: 'Labour Market Regulatory Authority (LMRA)',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Time and Attendance system for 350 staff with 17 devices installed. Email notifications implemented, CSB Rules applied and historical data migrated to the new system.',
  },
  {
    slug: 'ministry-of-foreign-affairs',
    clientName: 'Ministry of Foreign Affairs',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Time and Attendance devices deployed across 40 Bahrain embassies worldwide with centralised reporting. System configured to calculate and mark attendance using the local time of each embassy.',
  },
  {
    slug: 'ministry-of-islamic-affairs',
    clientName: 'Ministry of Islamic Affairs',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Time and Attendance system for 200 staff with online access. CSB Rules implemented, SMS notifications for out-time, software deployed on AWS.',
  },
  {
    slug: 'royal-humanitarian-foundation',
    clientName: 'Royal Humanitarian Foundation',
    clientType: 'Government',
    sector: 'Government',
    solution: 'New comprehensive HRMS system including HR, Personnel, Payroll, Time Attendance, Appraisal, Training, Self-Service and email notification.',
  },
  {
    slug: 'bahrain-institute-political-development',
    clientName: 'Bahrain Institute for Political Development (BIPD)',
    clientType: 'Government',
    sector: 'Government',
    solution: 'Time and Attendance system for 70 staff with online access. CSB Rules implemented, employee email notifications for out-time, software deployed on AWS.',
  },
  {
    slug: 'university-of-bahrain',
    clientName: 'University of Bahrain',
    clientType: 'Education',
    sector: 'Government',
    solution: '42 time attendance devices installed and integrated with Oracle for 1,200 staff.',
  },
  {
    slug: 'muller-middle-east',
    clientName: 'Muller Middle East',
    clientType: 'Private',
    sector: 'Private Sector',
    solution: 'Comprehensive HRMS system including HR, Personnel, Payroll, Time Attendance, Appraisal, Planning & Recruitment, Budgeting, Training, Self-Service and email notification.',
  },
];

export const CLIENTS = {
  government: [
    'Bahrain Bourse',
    'Bahrain Chamber of Commerce and Industry (BCCI)',
    'Bahrain Institute for Political Development (BIPD)',
    'BIX – Bahrain Internet Exchange',
    'Civil Service Bureau (CSB)',
    'Isa Cultural Centre',
    'Labour Market Regulatory Authority (LMRA)',
    'Ministry of Cabinet Affairs & Prime Minister Office',
    'Ministry of Labour',
    'NSSA - National Space Science Agency',
    'Ministry of Interior – Customs Affairs',
    'Ministry of Islamic Affairs',
    'Northern Area Municipality',
    'Real Estate Regulatory Authority (RERA)',
    'Royal Humanitarian Foundation (RHF)',
    'Survey & Land Registration Bureau (SLRB)',
    'University of Bahrain',
    'Urban Planning Development Authority',
  ],
  private: [
    'Ahmed Zayani & Sons',
    'Ahmed Mansoor Al Ali Co',
    'AJM Kooheji Group B.S.C',
    'Al Iman School',
    'Al Hilal Hospital',
    'Al Zayani Investment',
    'Al Zain Jewellery',
    'Ansari Engineering Services S.P.C',
    'Arab Open University',
    'Arab Architects',
    'Arabian Printing & Publishing House',
    'Arabtec Construction L.L.C (Bahrain Airport)',
    'AVM Labs',
    'Bahrain Medical Center (BMC)',
    'Bahrain Ship Repairing & Engineering Company B.S.C (BASREC)',
    'Balexco',
    'Banz Trading & Contracting W.L.L.',
    'BIIECO',
    'Bin Faquee',
    'Body Works',
    'CHAPO (BRF)',
    'City School',
    'CTS Middle East Bahrain W.L.L.',
    'Dahlman Middle East',
    'DAN Medical Center',
    'Dar Al Khaleej (GDN)',
    'Eagle Hills (Marassi)',
    'Etisalcom',
    'General Poultry Company (GPC)',
    'Ghousoon Spa & Saloon',
    'GTS - Global Lift Services Bahrain',
    'Gulf Assist',
    'Gulf Closures',
    'Gulf House Engineering',
    'Harmony Music Gate',
    'Ibn Al-Nafees Hospital Co. BSC',
    'iMachines',
    'International Motor Trading Agency W.L.L',
    'Invita Claims Management Company B.S.C',
    'Jah Consultancy',
    'Jalal Ionics WLL - Aqua Cool',
    'Jas Group W.L.L.',
    'Katana Torii Japanese Cuisine',
    'Keypoint',
    'Kims Health Hospital',
    'Kingdom University',
    'Lanterns Restaurants Group',
    'Linnas Medical Center',
    'Maersk Kanoo Bahrain W.L.L',
    'Maskati Commercials & Services',
    'Mohamed Salahuddin Consulting Engineering Bureau (MSCEB)',
    'Mueller Middle East',
    'Nass Corporation',
    'Novo Delizie And Mercato',
    'Panorama Contracting',
    'Racing Force Group',
    'Reckitt Benckiser Bahrain W.L.L',
    'Saudi Company for Environment',
    'Sika Gulf',
    'Talal Abu-Ghazaleh Global (BRF - Tag)',
    'The National Concrete Company W.L.L (N.C.C)',
    'Wave Infra Solution',
    'West Point',
    'Yaquby Stores',
    'Yateem Air Conditioning',
    'Yokogawa',
    'Zayani Otis Elevator Company',
  ],
  gcc: [
    'Doha Club',
    'KIA Motors - Qatar',
    'NetLink - Dubai',
    'Schuyler Security Technologies',
    'United Supplies - Dubai',
    'Workers Village - Abu Dhabi',
    'KIMS Health Hospital Group',
  ],
};

/** Homepage trust marquee — logos from TimeTech partner slider (time-tech.co) */
export const TRUST_LOGOS: { name: string; logo: string }[] = [
  { name: 'Ibn Al-Nafees Hospital Bahrain', logo: '/images/logos/trust/ibnalnafees.png' },
  { name: 'Royal Humanitarian Foundation', logo: '/images/logos/trust/rhf.png' },
  { name: 'Bahrain Bourse', logo: '/images/logos/trust/bahrainbourse.png' },
  { name: 'Survey & Land Registration Bureau (SLRB)', logo: '/images/logos/trust/slrb.png' },
  { name: 'Sawa University', logo: '/images/logos/trust/sawa-university.png' },
  { name: 'King Hamad University Hospital', logo: '/images/logos/trust/khuh.png' },
  { name: 'Vanderlande', logo: '/images/logos/trust/vanderlande.png' },
  { name: 'Anbar University', logo: '/images/logos/trust/anbar-university.png' },
  { name: 'ASRY', logo: '/images/logos/trust/asry.png' },
  { name: 'Al Mouwasat Hospital', logo: '/images/logos/trust/mouwasat.png' },
  { name: 'Nass Corporation', logo: '/images/logos/trust/nass.png' },
  { name: 'BSA', logo: '/images/logos/trust/bsa.png' },
  { name: 'Arab Open University', logo: '/images/logos/trust/aou.png' },
];

export const BLOG_POSTS = [
  {
    slug: 'top-5-benefits-biometric-attendance',
    title: 'Top 5 Benefits of Biometric Attendance Systems for GCC Enterprises',
    excerpt: 'Biometric attendance eliminates buddy-punching, reduces payroll errors and ensures full LMRA compliance. Here\'s why GCC enterprises are upgrading from legacy systems.',
    tags: ['Time Attendance', 'Biometric', 'LMRA'],
    publishedAt: '2026-02-15',
  },
  {
    slug: 'queue-management-government-sector',
    title: 'How Queue Management Systems Are Transforming Government Services in the GCC',
    excerpt: 'From ministries to municipal offices, TimeTech\'s queue management is cutting wait times and improving citizen satisfaction across Bahrain and the GCC.',
    tags: ['Queue Management', 'Government', 'GCC'],
    publishedAt: '2026-03-01',
  },
  {
    slug: 'rfid-asset-tracking-manufacturing',
    title: 'RFID Asset Tracking: A Complete Guide for GCC Manufacturing & Industrial Companies',
    excerpt: 'Everything you need to know about RFID asset tracking in GCC industrial environments, from hardware selection to warehouse management software integration.',
    tags: ['RFID', 'Asset Tracking', 'Warehouse'],
    publishedAt: '2026-03-15',
  },
  {
    slug: 'choosing-hr-software-bahrain',
    title: 'How to Choose the Right HRMS for Your GCC Business in 2026',
    excerpt: 'A practical guide to evaluating HRMS platforms for GCC businesses, covering LMRA compliance, WPS payroll, Arabic support, GOSI integration and mobile capabilities.',
    tags: ['HRMS', 'Payroll', 'Bahrain', 'GCC'],
    publishedAt: '2026-04-01',
  },
  // The three posts below preserve URL slugs that carried existing organic
  // rankings on the previous dthree.co site — see go-live redirect plan.
  {
    slug: 'salary-slip-format-bahrain',
    title: 'Salary Slip Format in Bahrain: What Every Payslip Must Include',
    excerpt: 'What a compliant Bahrain payslip needs to show, how WPS salary files tie into it, and how TimeTech HRMS generates both automatically from the same payroll run.',
    tags: ['Payroll', 'WPS', 'Bahrain'],
    publishedAt: '2026-04-15',
  },
  {
    slug: 'bahrain-labour-law-resignation-notice',
    title: 'Bahrain Labour Law: Resignation and Notice Period Rules Explained',
    excerpt: 'A practical overview of how notice periods generally work for indefinite and fixed-term contracts in Bahrain, and how HR teams track and document them correctly.',
    tags: ['Labour Law', 'Bahrain', 'HR Compliance'],
    publishedAt: '2026-04-22',
  },
  {
    slug: 'overtime-calculation-bahrain',
    title: 'How Overtime Is Calculated Under Bahrain Labour Law',
    excerpt: 'How overtime pay is generally structured for private-sector employees in Bahrain, and how automated time attendance removes the manual calculation error risk.',
    tags: ['Time Attendance', 'Overtime', 'Bahrain'],
    publishedAt: '2026-04-29',
  },
];

/** Which solution pages each blog post links to — also used in reverse on
 * solution pages to surface a "Related articles" block, so linking runs both ways. */
export const BLOG_RELATED_SOLUTIONS: Record<string, string[]> = {
  'top-5-benefits-biometric-attendance': ['time-attendance-system', 'timetech-application'],
  'queue-management-government-sector': ['queue-management-system'],
  'rfid-asset-tracking-manufacturing': ['rfid-asset-tracking'],
  'choosing-hr-software-bahrain': ['hr-payroll-software', 'timetech-application'],
  'salary-slip-format-bahrain': ['hr-payroll-software'],
  'bahrain-labour-law-resignation-notice': ['hr-payroll-software', 'timetech-application'],
  'overtime-calculation-bahrain': ['time-attendance-system', 'time-attendance-enterprise'],
};
